/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 18-Aug-2022 15:40:08
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 26
 * 稳定     : 是
 * 线性相位   : 是 (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\R2020b\extern\include\tmwtypes.h 
 */
const int num_taps = 26;
const float32_t Coeffs[26] = {
   0.001944941378276, 0.001612313594061,0.0002505781358229,-0.003547842552855,
   -0.01002341151401, -0.01660878711178, -0.01769870766454,-0.006532579826455,
    0.02136253621655,   0.0648488022861,   0.1159263792063,   0.1616494818787,
     0.1887093409862,   0.1887093409862,   0.1616494818787,   0.1159263792063,
     0.0648488022861,  0.02136253621655,-0.006532579826455, -0.01769870766454,
   -0.01660878711178, -0.01002341151401,-0.003547842552855,0.0002505781358229,
   0.001612313594061, 0.001944941378276
};
